### ISSUE TITLE
Categories are mandatory

### ISSUE THREAD

**Issue by denniskrol** [aboustayyef/InfraRead#5]
You can add sources without a category from the admin panel. 
Running `php artisan app:update_posts` will then throw an exception on line 92 of `rssFetcher.php` which returns the category_id (`$post->category_id = $this->source->category->id;`)
Maybe the admin should at least hint that a category is needed.

**Comment by aboustayyef** [comment]
Thanks for spotting this @denniskrol. when I made the categories optional, i adjusted the sources table but forgot about the posts table. I fixed the issue with the latest push. You'll need to perform a migration though.
